require "./spec_helper"

require "./sdl3/core/init_spec"
require "./sdl3/gfx/window_spec"
require "./sdl3/gfx/renderer_spec"
require "./sdl3/input/events_spec"
require "./sdl3/input/keyboard_spec"
require "./sdl3/core/error_spec"
require "./sdl3/core/timer_spec"
require "./sdl3/core/log_spec"
require "./sdl3/input/mouse_spec"
require "./sdl3/gfx/ttf_spec"
require "./sdl3/gfx/image_spec"
require "./sdl3/gfx/blendmode_spec"
require "./sdl3/gfx/pixels_spec"
require "./sdl3/input/game_pad_spec"
require "./sdl3/audio/audio_spec"
require "./sdl3/core/platform_spec"
